services:
  npiapp:
    container_name: npiapp
    image: omzig7/npi:waitress
    environment:
      - PYTHONUNBUFFERED=1
      - COMPOSE_PROJECT_NAME=npi
    ports:
      - 80:80
    volumes:
      - db:/app/db

volumes:
  db:
    driver: azure_file
    driver_opts:
      share_name: npifiles
      storage_account_name: npistorage1