services:
  npiapp:
    container_name: npiapp
    image: omzig7/npi:selfhost24
    environment:
      - PYTHONUNBUFFERED=1
      - COMPOSE_PROJECT_NAME=npi
    ports:
      - 5755:5755
    restart: always
    volumes:
    # - db1:/app/db
      - ".:/app"
      - type: bind
        source: N:\Projects\db # Folder the DB file is in
        target: /app/db # Where the app looks for DB file within docker environment. Do not change
      - type: bind
        source: N:\Projects\npi-selfhost\logs # Local log files.
        target: /app/logs # Where the app saves/loads logs within docker container. Do not change